[workspace]
[package]
version = "0.1.0"
name = "json-program"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
sp1-core = { git = "https://github.com/succinctlabs/sp1.git" }

serde = "1.0.197"